-- Healthcare Companies Database Export
-- Generated by Professional Healthcare Discovery System
-- 
CREATE TABLE IF NOT EXISTS healthcare_companies (
    url TEXT PRIMARY KEY,
    domain TEXT,
    company_name TEXT,
    country TEXT,
    sector TEXT,
    description TEXT,
    discovery_source TEXT,
    quality_score INTEGER,
    discovered_at TEXT,
    last_validated TEXT
);

