-- Healthcare Companies Database Export
-- Generated by Professional Healthcare Discovery System
-- 
CREATE TABLE IF NOT EXISTS healthcare_companies (
    url TEXT PRIMARY KEY,
    domain TEXT,
    company_name TEXT,
    country TEXT,
    sector TEXT,
    description TEXT,
    discovery_source TEXT,
    quality_score INTEGER,
    discovered_at TEXT,
    last_validated TEXT
);

INSERT OR REPLACE INTO healthcare_companies VALUES (
    'https://www.astrazeneca.com', 'astrazeneca.com', 'AstraZeneca - Research-Based BioPharmaceutical Company',
    'Sweden', 'Biotech', 'AstraZeneca is a global, science-led biopharmaceutical business and our innovative medicines are used by millions of patients worldwide.',
    'Validated list', , 
    '2025-07-09T16:29:47.199793', '2025-07-09T16:29:47.199797'
);
INSERT OR REPLACE INTO healthcare_companies VALUES (
    'https://www.ipsen.com', 'ipsen.com', 'Ipsen Global - A Biopharmaceutical Company - Innovation for Patient Care',
    'International', 'Biotech', 'Ipsen is a global biopharmaceutical company focused on innovation and specialty care to improve the lives of patients around the world.',
    'Validated list', , 
    '2025-07-09T16:29:47.206744', '2025-07-09T16:29:47.206746'
);
INSERT OR REPLACE INTO healthcare_companies VALUES (
    'https://www.b-braun.com', 'b-braun.com', 'B. Braun is a leading medical technology company.',
    'France', 'General Healthcare', 'With 64,000 employees, B. Braun is a true partner developing smart solutions and setting standards to drive advancements in health care. In 2024, the B. Braun Group recorded 9.1 billion euros in sales',
    'Validated list', , 
    '2025-07-09T16:29:47.211797', '2025-07-09T16:29:47.211799'
);
INSERT OR REPLACE INTO healthcare_companies VALUES (
    'https://www.sanofi.com', 'sanofi.com', 'R&D-Driven and AI-Powered Biopharma Company - Sanofi',
    'Germany', 'General Healthcare', 'Sanofi is a research & development-driven, AI-powered healthcare biopharma company committed to improving lives through innovative medicines & vaccines.',
    'Validated list', , 
    '2025-07-09T16:29:47.216727', '2025-07-09T16:29:47.216729'
);
INSERT OR REPLACE INTO healthcare_companies VALUES (
    'https://www.roche.com', 'roche.com', 'Roche - Doing now what patients need next',
    'Switzerland', 'General Healthcare', 'As a pioneer in healthcare, we have been committed to improving lives since the company was founded in 1896 in Basel, Switzerland. Today, Roche creates innovative medicines and diagnostic tests that h',
    'Validated list', , 
    '2025-07-09T16:29:47.221811', '2025-07-09T16:29:47.221813'
);
INSERT OR REPLACE INTO healthcare_companies VALUES (
    'https://www.fresenius.com', 'fresenius.com', 'Home - FSE',
    'France', 'General Healthcare', 'Main navigation



The Healthcare Group


Group Overview


Fresenius Kabi


Fresenius Helios


Management


Management Board


Supervisory Board


Corporate Governance


Compliance




Fields of Work
',
    'Validated list', , 
    '2025-07-09T16:29:47.226990', '2025-07-09T16:29:47.226992'
);
INSERT OR REPLACE INTO healthcare_companies VALUES (
    'https://www.healx.io', 'healx.io', 'Healx - AI drug discovery - Rare disease treatment',
    'Germany', 'General Healthcare', 'At Healx we use AI drug discovery to develop new treatments for rare diseases. We bring treatments from prediction to patient.',
    'Validated list', , 
    '2025-07-09T16:29:47.232245', '2025-07-09T16:29:47.232247'
);
INSERT OR REPLACE INTO healthcare_companies VALUES (
    'https://www.aidence.com', 'aidence.com', 'Homepage - Aidence',
    'Germany', 'Medical Imaging', 'Aidence provides AI radiology solutions for the lung cancer pathway, empowering physicians to deliver better patient care. RadNet subsidiary.',
    'Validated list', , 
    '2025-07-09T16:29:47.237415', '2025-07-09T16:29:47.237418'
);
INSERT OR REPLACE INTO healthcare_companies VALUES (
    'https://www.grifols.com', 'grifols.com', 'Biopharma & Healthcare Solutions - Grifols',
    'International', 'General Healthcare', 'Explore Grifols'' comprehensive, innovative and patient-centric biopharma and healthcare solutions.',
    'Validated list', , 
    '2025-07-09T16:29:47.242466', '2025-07-09T16:29:47.242467'
);
INSERT OR REPLACE INTO healthcare_companies VALUES (
    'https://www.mindmaze.com', 'mindmaze.com', 'Home - MindMaze',
    'Sweden', 'Medical Devices', 'Medicine

MindPod
Intento
Toap Run


Care

MindMotion GO
MindMotion PRO


Monitor

Physilog
Brain Vitals


About

MindMaze
Clinical pipeline
Healthcare


Media
Testimonials
Careers
Contact',
    'Validated list', , 
    '2025-07-09T16:29:47.249218', '2025-07-09T16:29:47.249221'
);
